# Generated by Django 5.0.3 on 2024-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equb',
            name='equb_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
